### ISSUE TITLE
Ignore regions

### ISSUE THREAD

**Issue by robinweide** [zhanyinx/CaTCH_R#1]
Dear Yinxiu,

After running your tool I found that there are a lot of TAD-boundaries placed in regions with either no signal (rowsum of a bin ~ 0) or at centromeric sites.

Would it be possible to give users the option to specify particular bins in their input, that should not be regarded as valid sites to place a TAD-border? 

Thanks,
Robin

**Comment by zhanyinx** [comment]
Dear Robin,

I apologise that I missed your comment. 

The way the algorithm works makes difficult to avoid special bins to be excluded. The reason is that you have to position the excluded boundary somewhere else (shifting it) and there is no an obvious way where to position it.
 
Zhan

**Comment by robinweide** [comment]
Hi Zhan,

I see. I tried to circumvent this by indeed shifting the bins in the CaTCH-input (e.g. remove bin 3 and substract 1 from all bins > 3) and reverse-shifting the bins in the CaTCH-output . This works rather well.

Best,
Robin
