### ISSUE TITLE
CTCF-enrichment

### ISSUE THREAD

**Issue by robinweide** [zhanyinx/CaTCH_R#5]
I'm trying to reproduce figure 2A of your paper. However, I do not get this nice 'hump' in the enrichment through the RI-range. How do you calculate this CTCF-enrichment?

**Comment by zhanyinx** [comment]
Hi,

I expanded all the boundaries 20kb upstream and downstream (boundaries region = 40kb).
I calculated the average number of CTCF peaks inside the boundaries region. I calculate the average number of CTCF sites in 40kb not overlapping the boundaries.

Suppose 
N =total number of CTCF sites,
G = genome size
m = number of CTCF sites at boundaries
nb = number of boundaries

ab= average CTCF at boundaries = m/nb
anb = average CTCF at no-boundaries = (N-m)/(G-nm*40000)*40000

The enrichment is defined as
ab/anb
